name: Build Docker Stack

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: taskdb
          POSTGRES_USER: devuser
          POSTGRES_PASSWORD: devpass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        run: |
          cd backend
          docker build -t devops-backend .

      - name: Build frontend Docker image
        run: |
          cd frontend
          docker build -t devops-frontend .
