name: Build and Push to ECR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push backend image
        run: |
          docker build -t devops-backend ./backend
          docker tag devops-backend:latest 746669200695.dkr.ecr.us-east-1.amazonaws.com/devops-backend:latest
          docker push 746669200695.dkr.ecr.us-east-1.amazonaws.com/devops-backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t devops-frontend ./frontend
          docker tag devops-frontend:latest 746669200695.dkr.ecr.us-east-1.amazonaws.com/devops-frontend:latest
          docker push 746669200695.dkr.ecr.us-east-1.amazonaws.com/devops-frontend:latest
